### ISSUE TITLE
Timer not updating when boss checklist is open

### ISSUE THREAD

**Issue by Maxoverpower** [Voxelse/LiveSplit.Terraria#5]
As you can see in this included video, when the boss checklist is opened, livesplit's timer doesn't show any updates, **as if the window is minimised**, even though it responds to hotkey commands like start/stop. This issue likely started with the latest version of autosplitter.
https://youtu.be/_P2ZB95IdEU

Note: if you start the timer, and then open boss checklist - livesplit will be responsive until the timer is reset.

As you may also notice from the video, the boss icons are blank for me. That started even before the latest update - likely as soon as I switched to Windows 11, so it may somehow be the cause.

**Comment by Voxelse** [comment]
Was the game running when you had this issue?
It seems that there are some errors but these should only occurs when the game is closed and when trying to start the timer manually.
5d9d4a2 should fix this.

And for boss icons it seems that you have the same problem as #1 
The integrated web page uses a wrapper of internet explorer so IE is probably missing on your PC. It's sad to use IE but I'd otherwise have to integrate a framework that would bloat the size of the autosplitter only to display a web page.
